# Generated by Django 6.0.5 on 2026-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название народа')),
                ('flag_emoji', models.CharField(default='🏳️', max_length=10, verbose_name='Флаг (эмодзи)')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('history_text', models.TextField(verbose_name='История народа')),
                ('language_features', models.TextField(help_text='Напишите про грамматику, интересные факты, алфавит и т.д.', verbose_name='Особенности языка')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='peoples/photos/', verbose_name='Фото 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='peoples/photos/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='peoples/photos/', verbose_name='Фото 3')),
                ('video_url', models.URLField(blank=True, help_text='Вставьте ссылку на YouTube или Vimeo', verbose_name='Ссылка на видео')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='peoples/audio/', verbose_name='Аудио (песня/речь)')),
            ],
            options={
                'verbose_name': 'Народ',
                'verbose_name_plural': 'Народы',
            },
        ),
    ]
