# Generated by Django 6.0.5 on 2026-05-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='video_embed_code',
            field=models.TextField(blank=True, help_text='Для ВКонтакте: скопируйте embed код из видео', verbose_name='Код для вставки (Для вк)'),
        ),
        migrations.AddField(
            model_name='nation',
            name='video_host',
            field=models.CharField(choices=[('vk', 'ВКонтакте'), ('rutube', 'RUTUBE')], default='rutube', help_text='Выберите где разместить видео', max_length=20, verbose_name='Видеохостинг'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
